#!/usr/bin/env bash
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Wrapper for thrift that attempts to use the system thrift if it's of the expected version,
# otherwise it bootstraps a new one.
set -e -u

if [[ $# -lt 1 ]]; then
  cat <<EOF
Usage: thriftw EXPECTED_THRIFT_VERSION THRIFT_ARGS...

Run the thrift compiler at EXPECTED_THRIFT_VERSION with THRIFT_ARGS, bootstrapping if necessary.
EOF
fi
expected_version=$1
shift

HERE=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)

function check_thrift_version() {
  local readonly thrift="$1"

  [[ $("${thrift}" --version) = "Thrift version ${expected_version}" ]]
}

function check_thrift_gen_lang() {
  local readonly thrift="$1"
  local readonly gen_identifier="$2"

  "${thrift}" -help 2>&1 | grep -q "${gen_identifier}:"
}

function compatible_thrift() {
  local readonly thrift="$1"

  [[ -x "${thrift}" ]] && \
  check_thrift_version "${thrift}" && \
  check_thrift_gen_lang "${thrift}" "java (Java)" && \
  check_thrift_gen_lang "${thrift}" "js (Javascript)" && \
  check_thrift_gen_lang "${thrift}" "html (HTML)" && \
  check_thrift_gen_lang "${thrift}" "py (Python)"
}

function compatible_system_thrift() {
  if [[ -n "${THRIFT:-}" ]]; then
    if compatible_thrift "${THRIFT}"; then
      echo "${THRIFT}"
      return
    fi
    echo "THRIFT is set but not compatible with expected version ${expected_version}!" >&2
    exit 1
  fi

  if compatible_thrift "${HERE}/thrift"; then
    echo "${HERE}/thrift"
  else
    which -a thrift 2> /dev/null | while read thrift; do
      if compatible_thrift "${thrift}"; then
         echo "${thrift}"
         return
      fi
    done
  fi
}

thrift="$(compatible_system_thrift)"
if [[ -z "${thrift}" ]]; then
  echo "Failed to find a thrift ${expected_version} binary." >&2
  echo "Install thrift ${expected_version} or set THRIFT to its path." >&2
  exit 1
fi

exec "${thrift}" "$@"
